Creating Tensors

In [1]:
import tensorflow as tf

In [2]:
tf_string = tf.Variable('hello world',tf.string)
tf_string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello world'>

In [3]:
tf_integer = tf.Variable(123,tf.int64)
tf_integer

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [4]:
tf_float = tf.Variable(123.5,tf.float32)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.5>

Check rank of tensor

In [5]:
tf_float_r2 = tf.Variable([[123.5],[12.4]],tf.float32)
tf.rank(tf_float_r2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Check shape of tensor

In [6]:
tf_float_r2.shape

TensorShape([2, 1])

In [8]:
tf_float_r3 = tf.Variable([[[123.5],[12.4]]],tf.float32)
print(tf.rank(tf_float_r3))
tf_float_r3.shape

tf.Tensor(3, shape=(), dtype=int32)


TensorShape([1, 2, 1])

Reshaping tensors

In [10]:
tf1 = tf.Variable([1,1,1,1,1,1],tf.int32)
tf1.shape

TensorShape([6])

In [11]:
tf2=tf.reshape(tf1,[2,3])
tf2.shape

TensorShape([2, 3])

In [12]:
tf2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [14]:
constant=tf.constant(1,tf.int32)
constant

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [1]:
import sys
sys.executable

'c:\\program files\\python38\\python.exe'